"""
TEACHING DEMO: Full Platform Exploration
Recorded: 2025-11-09
Duration: ~15min
Coverage: Login, Properties, Calendar, Analytics, Inbox, Settings, Integrations, Multi-Unit

This demo covers:
- Property management (view, edit tabs, custom amenities, price rules, fees)
- Calendar operations (filters, pricing mode, lead creation, blocking)
- Analytics exploration (date ranges, filters, metrics)
- Inbox messaging (templates, filters, lead conversation)
- Settings navigation (agency settings, templates, triggers, pre-arrival form)
- Integrations (PayPal toggles)
- Multi-unit property creation (unit types, units management)
- User profile updates
"""

import re
from playwright.sync_api import Playwright, sync_playwright, expect

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://platform.test.hostfully.com/app/#/login")
    page.get_by_test_id("email").click()
    page.get_by_test_id("email").fill("daniel+pmp@hostfully.com")
    page.get_by_test_id("password").click()
    page.get_by_test_id("password").fill("pas123")
    page.get_by_test_id("submit-button").click()
    page.get_by_role("button", name="gerenciadordeprop2").click()
    page.get_by_role("link", name="Propriedades").click()
    page.get_by_text("-timezone(early)").click()
    page.get_by_test_id("property-settings-tab-descriptions").click()
    page.get_by_test_id("property-settings-tab-photos").click()
    page.get_by_test_id("property-settings-tab-amenities").click()
    page.get_by_test_id("custom-amenities-button").click()
    page.get_by_test_id("name").click()
    page.get_by_test_id("name").fill("custom amenities")
    page.get_by_test_id("modal-form-submit-button").click()
    page.get_by_role("row", name="custom amenities 1-timezone(").get_by_test_id("table-row-edit-button").click()
    page.get_by_test_id("name").click()
    page.get_by_test_id("name").fill("custom amenities e edição")
    page.get_by_test_id("modal-form-submit-button").click()
    page.get_by_test_id("property-settings-tab-pricing").click()
    page.get_by_test_id("price-rules-header-button").click()
    page.get_by_test_id("priceRule.name").click()
    page.get_by_test_id("priceRule.name").fill("regra de preço")
    page.get_by_test_id("priceRule.type").select_option("SHORT_STAY_PREMIUM")
    page.get_by_test_id("priceRule.priceModifier").click()
    page.get_by_test_id("priceRule.priceModifier").fill("025")
    page.get_by_test_id("priceRule.priceModifierThreshold").click()
    page.get_by_test_id("priceRule.priceModifierThreshold").fill("03")
    page.get_by_role("radio", name="Todas as propriedades").check()
    page.get_by_role("radio", name="Propriedades selecionadas").check()
    page.get_by_test_id("filter-icon").click()
    page.get_by_test_id("appliesToStatus").select_option("active")
    page.locator(".select__indicator").click()
    page.get_by_test_id("appliesToTags-field-container").locator("svg").click()
    page.get_by_test_id("appliesToProperties-field-container").locator("svg").nth(1).click()
    page.get_by_role("option", name="-timezoneTestBR->Flo").click()
    page.get_by_role("option", name="3-timezone").click()
    page.get_by_text("CancelarSalvar").click()
    page.get_by_test_id("price-rule-submit-button").click()
    page.get_by_test_id("property-settings-tab-fees-and-policies").click()
    page.get_by_test_id("property-fees-taxes-button").click()
    page.get_by_test_id("name").click()
    page.get_by_test_id("name").fill("taxa")
    page.get_by_test_id("type").select_option("TAX")
    page.get_by_test_id("amount").click()
    page.get_by_test_id("amount").fill("12")
    page.get_by_test_id("scope.amount").select_option("PER_GUEST")
    page.get_by_role("radio", name="Sim").check()
    page.get_by_test_id("modal-form-submit-button").click()
    page.get_by_test_id("type").select_option("CUSTOM")
    page.get_by_test_id("modal-form-submit-button").click()
    page.get_by_test_id("nav-item-common.calendar").click()
    page.get_by_test_id("calendar-today-button").click()
    page.get_by_test_id("mode-switcher-button-PRICING").click()
    page.get_by_test_id("filter-icon").click()
    page.get_by_test_id("location").select_option("Berlin")
    page.get_by_test_id("location").select_option("")
    page.get_by_test_id("agentUid").select_option("8810aa29-baef-406b-8079-f1b8cc61b1ab")
    page.get_by_test_id("agentUid").select_option("82971990-6641-47e3-9c74-809d3641ac8b")
    page.get_by_test_id("agentUid").select_option("8810aa29-baef-406b-8079-f1b8cc61b1ab")
    page.get_by_test_id("amenities-field-container").locator("svg").click()
    page.get_by_role("option", name="24 checkin").click()
    page.get_by_role("button", name="Remove 24 checkin").click()
    page.get_by_test_id("amenities-field-container").locator("svg").click()
    page.get_by_test_id("tags-field-container").locator("svg").click()
    page.get_by_test_id("tags-field-container").locator("svg").click()
    page.get_by_test_id("submit-filters").click()
    page.locator("div:nth-child(5) > div:nth-child(5)").click()
    page.locator(".body-day-cell.date-before-today.width-70.weekend > .day-cell-selection-pricing-container").click()
    page.get_by_test_id("pricing-modal-reset-button").click()
    page.get_by_test_id("nav-item-common.analytics").click()
    page.get_by_test_id("presetDateRange").select_option("TODAY")
    page.get_by_test_id("presetDateRange").select_option("TOMORROW")
    page.get_by_test_id("presetDateRange").select_option("LAST_WEEK")
    page.get_by_test_id("presetDateRange").select_option("THIS_WEEK")
    page.get_by_test_id("presetDateRange").select_option("NEXT_WEEK")
    page.get_by_test_id("presetDateRange").select_option("LAST_MONTH")
    page.get_by_test_id("presetDateRange").select_option("THIS_MONTH")
    page.get_by_test_id("presetDateRange").select_option("NEXT_MONTH")
    page.get_by_test_id("presetDateRange").select_option("THIS_QUARTER")
    page.get_by_test_id("analytics-list-item-placeholder").first.click()
    page.get_by_test_id("analytics-list-item-placeholder").nth(1).click()
    page.get_by_test_id("analytics-list-item-placeholder").nth(2).click()
    page.get_by_test_id("analytics-list-item-placeholder").nth(3).click()
    page.get_by_test_id("analytics-list-item-placeholder").nth(4).click()
    page.get_by_test_id("channelPieChart-container").get_by_role("img").nth(1).click()
    page.get_by_text("US$ 78").click()
    page.get_by_test_id("analytics-list-revPar").get_by_text("US$").click()
    page.get_by_text("%").click()
    page.get_by_text("112").click()
    page.get_by_text("US$ 8,684 mil").click()
    page.get_by_test_id("type").select_option("PROPERTY_PERFORMANCE")
    page.get_by_test_id("type").select_option("TEAM_PERFORMANCE")
    page.get_by_test_id("dateType").select_option("CHECK_OUT")
    page.get_by_test_id("dateType").select_option("CHECK_IN")
    page.get_by_test_id("dateType").select_option("RESERVATION")
    page.get_by_test_id("dateType").select_option("LEAD_CREATION")
    page.get_by_test_id("propertyUid").select_option("b37f48a1-4d48-4603-8801-3aee18610968")
    page.get_by_test_id("propertyUid").select_option("6a4c28e7-3021-4c3f-bb90-058f987da358")
    page.get_by_test_id("propertyUid").select_option("")
    page.get_by_test_id("channel").select_option("HOSTFULLY")
    page.get_by_test_id("channel").select_option("VRBO")
    page.get_by_test_id("channel").select_option("")
    page.get_by_test_id("timeReference").select_option("LAST_YEAR")
    page.get_by_role("button", name="gerenciadordeprop2").click()
    page.get_by_role("link", name="Integrações").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator("#manage-PAYPAL").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator(".bootstrap-switch.bootstrap-switch-wrapper.bootstrap-switch-off > .bootstrap-switch-container > .bootstrap-switch-label").first.click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator(".bootstrap-switch.bootstrap-switch-wrapper.bootstrap-switch-off > .bootstrap-switch-container > .bootstrap-switch-label").first.click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator("div:nth-child(3) > .property-details > p:nth-child(2) > .bootstrap-switch > .bootstrap-switch-container > .bootstrap-switch-label").click()
    page.get_by_role("button", name="gerenciadordeprop2").click()
    page.get_by_role("link", name="Configurações de Agência").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Account Status").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Service Providers").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Rental Conditions").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Email Settings").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Direct Booking Website").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="White Labeling").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Main Settings").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("button", name="Update").click()
    page.get_by_role("button", name="gerenciadordeprop2").click()
    page.get_by_role("link", name="Modelos e Gatilhos").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Custom Templates").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Triggers").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Custom Data").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Reviews").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Pre-Arrival Form").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator("div:nth-child(3) > .row > div:nth-child(2) > .checkbox > label > input").first.check()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator("div:nth-child(4) > .row > div:nth-child(2) > .checkbox > label > input").first.check()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator("div:nth-child(5) > .row > div:nth-child(2) > .checkbox > label > input").first.check()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator("div:nth-child(6) > div:nth-child(5) > .row > div:nth-child(2) > .checkbox > label > input").check()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("checkbox", name="Optional").first.check()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Scheduled Messages").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.get_by_role("link", name="Message Log").click()
    page.get_by_test_id("nav-item-common.inbox").click()
    page.get_by_test_id("inbox-message-editor-editable-area").click()
    page.get_by_test_id("inbox-message-editor-editable-area").fill("olá, inbox")
    page.get_by_test_id("send-button-EMAIL").click()
    page.get_by_test_id("toggle-template-selector-icon").click()
    page.get_by_role("button", name="Nova solicitação de reserva").click()
    page.get_by_test_id("send-button-EMAIL").click()
    page.get_by_test_id("filter-icon").click()
    page.get_by_test_id("showUnreadOnly").select_option("true")
    page.get_by_test_id("showUnreadOnly").select_option("")
    page.get_by_test_id("leadChannel").select_option("HOSTFULLY")
    page.get_by_test_id("leadChannel").select_option("VRBO")
    page.get_by_test_id("leadChannel").select_option("BOOKING_COM")
    page.get_by_test_id("submit-filters").click()
    page.get_by_test_id("leadChannel").select_option("")
    page.get_by_test_id("submit-filters").click()
    page.get_by_test_id("agentUid").select_option("8810aa29-baef-406b-8079-f1b8cc61b1ab")
    page.get_by_test_id("submit-filters").click()
    page.get_by_test_id("agentUid").select_option("")
    page.get_by_test_id("submit-filters").click()
    page.get_by_test_id("sortBy").select_option("SORT_BY_LEAD_CHECK_IN_DATE")
    page.get_by_text("Limpar filtrosAplicar filtros").click()
    page.get_by_test_id("propertyUid").select_option("b37f48a1-4d48-4603-8801-3aee18610968")
    page.get_by_test_id("submit-filters").click()
    page.get_by_test_id("propertyUid").select_option("0d8d3a74-6ced-4f88-a3d3-47078bece67f")
    page.get_by_test_id("submit-filters").click()
    page.get_by_test_id("propertyUid").select_option("")
    page.get_by_test_id("leadStatus").select_option("RELEVANT")
    page.get_by_test_id("submit-filters").click()
    page.get_by_test_id("inbox-lead-selector").click()
    page.get_by_test_id("lead-selector-item-b64900b2-dab9-4e4a-9587-84d8979e2780").click()
    page.get_by_test_id("inbox-message-editor-editable-area").click()
    page.get_by_test_id("inbox-message-editor-editable-area").fill("olá")
    page.get_by_test_id("send-button-EMAIL").click()
    page.get_by_test_id("inbox-lead-selector").click()
    page.get_by_test_id("lead-selector-item-285892cd-8379-41e4-8229-ec95a3da292d").click()
    page.get_by_test_id("lead-view-button").click()
    page.get_by_role("tab", name="Informação ao cliente").click()
    page.get_by_role("tab", name="Cronograma de pagamento").click()
    page.get_by_role("tab", name="Detalhes da estadia").click()
    page.get_by_test_id("extraNotes").click()
    page.get_by_test_id("extraNotes").fill("nota extra")
    page.get_by_test_id("flightNumber").click()
    page.get_by_test_id("flightNumber").fill("1234512341")
    page.get_by_test_id("reasonForTrip").click()
    page.get_by_test_id("reasonForTrip").fill("motivo da viagem")
    page.get_by_test_id("button-submit").click()
    page.get_by_test_id("lead-view-button").click()
    page.get_by_role("tab", name="Notas internas de convidados").click()
    page.get_by_test_id("reviewByHost.notes").click()
    page.get_by_test_id("reviewByHost.notes").fill("notas")
    page.get_by_test_id("button-submit").click()
    page.get_by_role("button", name="gerenciadordeprop2").click()
    page.get_by_role("link", name="Propriedades").click()
    page.locator("#property-actions-container-b37f48a1-4d48-4603-8801-3aee18610968").get_by_test_id("property-actions-menu").click()
    page.get_by_role("menuitem", name="Duplicar").click()
    page.get_by_test_id("add-property-button").click()
    page.get_by_role("menuitem", name="Propriedade Multi-Unidade").click()
    page.get_by_test_id("propertyDetails.propertyName").click()
    page.get_by_test_id("propertyDetails.propertyName").fill("multiunit")
    page.get_by_test_id("propertyDetails.securityDeposit").click()
    page.get_by_test_id("propertyDetails.securityDeposit").fill("50")
    page.get_by_test_id("propertyAddress.addressLine1").click()
    page.get_by_test_id("propertyAddress.addressLine1").fill("endereço")
    page.get_by_test_id("propertyAddress.state").click()
    page.get_by_test_id("propertyAddress.state").fill("SP")
    page.get_by_test_id("propertyAddress.city").click()
    page.get_by_test_id("propertyAddress.city").fill("caçapva")
    page.get_by_test_id("propertyAddress.zipCode").click()
    page.get_by_test_id("propertyAddress.zipCode").fill("12282495")
    page.get_by_test_id("form-footer").get_by_test_id("save-button").click()
    page.get_by_test_id("property-settings-tab-unit-types").click()
    page.get_by_test_id("add-unit-type-button").click()
    page.get_by_test_id("propertyDetails.propertyName").click()
    page.get_by_test_id("propertyDetails.propertyName").fill("tipodeunidade de multunit")
    page.get_by_test_id("propertyDetails.propertySize").click()
    page.get_by_test_id("propertyDetails.propertySize").fill("80")
    page.get_by_test_id("capacityDetails.bedroomCount").select_option("3")
    page.get_by_test_id("capacityDetails.bedCount").select_option("3")
    page.get_by_test_id("capacityDetails.baseGuests").click()
    page.get_by_test_id("capacityDetails.baseGuests").fill("5")
    page.get_by_test_id("capacityDetails.maxGuests").click()
    page.get_by_test_id("capacityDetails.maxGuests").fill("10")
    page.get_by_test_id("capacityDetails.extraGuestFee").click()
    page.get_by_test_id("capacityDetails.extraGuestFee").fill("020")
    page.get_by_test_id("propertyPricingFeesTaxes.nightlyBasePrice").click()
    page.get_by_test_id("propertyPricingFeesTaxes.nightlyBasePrice").fill("090")
    page.get_by_test_id("propertyPricingFeesTaxes.securityDeposit").click()
    page.get_by_test_id("propertyPricingFeesTaxes.securityDeposit").fill("010")
    page.get_by_test_id("propertyPricingFeesTaxes.cleaningFee").click()
    page.get_by_test_id("propertyPricingFeesTaxes.cleaningFee").fill("15")
    page.get_by_test_id("propertyPricingFeesTaxes.cleaningFeeTax").click()
    page.get_by_test_id("propertyPricingFeesTaxes.cleaningFeeTax").fill("30")
    page.get_by_test_id("form-footer").get_by_test_id("save-button").click()
    page.get_by_test_id("property-settings-tab-units").click()
    page.get_by_test_id("extraUnits-field-container").get_by_text("units").click()
    page.get_by_test_id("extraUnits").click()
    page.get_by_test_id("extraUnits").fill("5")
    page.get_by_test_id("add-extra-units-button").click()
    page.get_by_role("button", name="Save Units").click()
    page.get_by_test_id("unit-row-cade0c56-631f-43a1-a6a9-8736714a284c").get_by_text("Active").click()
    page.get_by_test_id("unit-row-cade0c56-631f-43a1-a6a9-8736714a284c").get_by_text("Active").click()
    page.get_by_test_id("unit-row-cade0c56-631f-43a1-a6a9-8736714a284c").get_by_role("button", name="").click()
    page.get_by_role("menuitem", name="Deactivate").click()
    page.get_by_test_id("confirm-button").click()
    page.get_by_test_id("unit-row-cade0c56-631f-43a1-a6a9-8736714a284c").get_by_role("button", name="").click()
    page.get_by_role("menuitem", name="Deletar").click()
    page.get_by_test_id("confirm-button").click()
    page.get_by_role("button", name="Save Units").click()
    page.get_by_test_id("selectedPropertyUid").select_option("4c46a789-c890-4950-91c2-2dad6d84bc86")
    page.goto("https://platform.test.hostfully.com/app/#/property/4c46a789-c890-4950-91c2-2dad6d84bc86")
    page.get_by_test_id("selectedPropertyUid").select_option("0d8d3a74-6ced-4f88-a3d3-47078bece67f")
    page.goto("https://platform.test.hostfully.com/app/#/property/0d8d3a74-6ced-4f88-a3d3-47078bece67f")
    page.get_by_test_id("selectedPropertyUid").select_option("b37f48a1-4d48-4603-8801-3aee18610968")
    page.goto("https://platform.test.hostfully.com/app/#/property/b37f48a1-4d48-4603-8801-3aee18610968")
    page.get_by_role("link", name="Propriedades").click()
    page.get_by_test_id("filter-icon").click()
    page.get_by_role("link", name="User profile").click()
    page.get_by_test_id("firstName").click()
    page.get_by_test_id("firstName").fill("Daniel teste")
    page.get_by_test_id("lastName").click()
    page.get_by_role("button", name="Enviar").click()
    page.get_by_test_id("ssoEmail").fill("daniel@hostfully.com")
    page.get_by_role("button", name="Enviar").click()
    page.get_by_role("button", name="Enviar").click()
    page.get_by_test_id("nav-item-common.calendar").click()
    page.get_by_test_id("filter-icon").click()
    page.get_by_test_id("filter-icon").click()
    page.get_by_test_id("agentUid").select_option("")
    page.get_by_test_id("submit-filters").click()
    page.get_by_test_id("mode-switcher-button-BOOKING").click()
    page.locator(".stacked-calendar-body-row > div:nth-child(48)").first.click()
    page.locator(".stacked-calendar-body-row > div:nth-child(55)").first.click()
    page.get_by_test_id("childrenCount").select_option("1")
    page.get_by_test_id("infantCount").select_option("1")
    page.get_by_test_id("notes").click()
    page.get_by_test_id("notes").fill("lead pelo calendario")
    page.get_by_test_id("lead-status-button-BOOKED_BY_AGENT").click()
    page.get_by_test_id("button-submit").click()
    page.get_by_test_id("email").fill("daniel@hostfully.com")
    page.get_by_test_id("button-submit").click()
    page.get_by_test_id("button-submit").click()
    page.locator(".stacked-calendar-body-container-scrollable > div:nth-child(2) > div:nth-child(32)").click()
    page.locator(".stacked-calendar-body-container-scrollable > div:nth-child(2) > div:nth-child(40)").click()
    page.get_by_test_id("lead-status-button-BLOCKED").click()
    page.get_by_test_id("notes").click()
    page.get_by_test_id("notes").fill("bloqueio de calendario")
    page.locator("#from").click()
    page.get_by_role("option", name="Choose terça-feira, 11 de").click()
    page.locator("#to").click()
    page.get_by_role("option", name="Choose quarta-feira, 19 de").click()
    page.get_by_role("button", name="Salvar").click()
    page.get_by_role("button", name="gerenciadordeprop2").click()
    page.get_by_role("link", name="Integrações").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator(".bootstrap-switch.bootstrap-switch-wrapper.bootstrap-switch-on.bootstrap-switch-mini.bootstrap-switch-id-channelSwitch-pricelabs > .bootstrap-switch-container > .bootstrap-switch-label").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator(".bootstrap-switch.bootstrap-switch-wrapper.bootstrap-switch-mini.bootstrap-switch-id-channelSwitch-pricelabs > .bootstrap-switch-container > .bootstrap-switch-label").click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator(".bootstrap-switch-label").first.click()
    page.locator("[data-testid=\"legacy-page-frame\"]").content_frame.locator("#properties div").filter(has_text="-timezone(early)ON OFFSuccess !").locator("span").nth(2).click()
    
    # ---------------------
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)

